### ISSUE TITLE
README missing alot of Details

### ISSUE THREAD

**Issue by ameentalahmeh** [FACK1/SAMO#23]
Your README missing A lot of Details that must be to show your website design, Architecture, and else.

**Comment by m4v15** [comment]
I agree, I would also add some instructions for running the website locally:

- Clone the repo: `git clone ....`
- Install node modules: `npm i`
- Run tests: `npm test`

**Comment by orjwan98** [comment]
We updated the readMe. Please close the issue, thanks.

**Comment by m4v15** [comment]
I would maybe try to add a little bit of styling to it to make it easier to read?

**Comment by m4v15** [comment]
but also it is up to @ameentalahmeh to close this

**Comment by safaaamro** [comment]
do it
