### ISSUE TITLE
Form validation?

### ISSUE THREAD

**Issue by m4v15** [FACK1/SAMO#38]
You could look into some client side form validation to stop people submitting empty strings.

You could do it just using html 5 attributes - see [here](https://www.sitepoint.com/client-side-form-validation-html5/)

Or you could do it with JS and even have fancy CSS happening when it fails validation - see [here](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation)

**Comment by orjwan98** [comment]
It's been done. Please close the issue, thanks.
